let start = document.getElementById('start');
let budgetValue = document.getElementsByClassName('budget-value');
let daybudgetValue = document.getElementsByClassName('daybudget-value');
let levelValue = document.getElementsByClassName('level-value');
let expensesValue = document.getElementsByClassName('expenses-value');
let optionalexpensesValue = document.getElementsByClassName('optionalexpenses-value');
let incomeValue = document.getElementsByClassName('income-value');
let monthsavingsValue = document.getElementsByClassName('monthsavings-value');
let yearsavingsValue = document.getElementsByClassName('yearsavings-value');
let expensesItem = document.getElementsByClassName('expenses-item');
let expensesItemBtn = document.getElementsByTagName('button')[0];
let countBudgetBtn = document.getElementsByTagName('button')[2];
let optionalexpensesItem = document.querySelectorAll('.optionalexpenses-item');
let chooseIncomeLabel = document.querySelector('.choose-income-label');
let choosePercent = document.querySelector('.choose-percent');
let chooseSum = document.querySelector('.choose-sum');
let yearValue = document.querySelector('.year-value');
let monthValue = document.querySelector('.month-value');
let dayValue = document.querySelector('.day-value');

console.log(dayValue);
